# Form implementation generated from reading ui file 'RawUI/PlayerCard.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtCore import pyqtSignal, QRect, QSize, Qt, QCoreApplication
from PyQt6.QtWidgets import (
    QWidget,
    QFrame,
    QDialog,
    QGroupBox,
    QHBoxLayout,
    QVBoxLayout,
    QLabel,
    QPushButton,
    QGridLayout,
    QInputDialog,
)
from UI.playerCard.SpellCellsObj import Ui_SpellCellObj
from UI.playerCard.spellContainer import spellGroup as SpellCont
from UI.playerCard.statusObj import StatusObj
from UI.playerCard.statusContainer import StatusContainer as StatusCont
from OtherPyFiles.characterclass import Character


# class Ui_PlayerCard(QWidget):
class Ui_PlayerCard(QWidget):
    needToSend = pyqtSignal(object)
    scratch = {"1": 2, "2": 2, "3": 4, "4": 4, "5": 5, "6": 5}

    def __init__(self, char=Character(), client=None):
        super().__init__()
        self.character = char
        self.setupUi()

    def setupUi(self):
        self.initLayout = QVBoxLayout(self)
        self.mainGroup = QGroupBox()
        self.initLayout.addWidget(self.mainGroup)
        self.mainLayout = QVBoxLayout(self.mainGroup)

        self.firstChars = QGridLayout()
        self.firstChars.setContentsMargins(5, 10, 5, 5)
        self.mainLayout.addLayout(self.firstChars, 2)
        self.firstCharsInit()

        self.secondChars = QHBoxLayout()
        self.mainLayout.addLayout(self.secondChars, 3)
        self.secondCharsInit()

        self.changeLevelDialog = QInputDialog(self)

    def charLevelUpdate(self, data):
        self.character.setLevel(data.get("level", -1))
        self.character.setXp(data.get("experience", 0))
        self.expUPD(
            self.character.Stats.get("experience", 0), self.character.getNextLevelExp()
        )
        self.needToSend.emit(
            [["newLevel", data.get("level", -1)], ["newExp", data.get("experience", 0)]]
        )

    def firstCharsInit(self):
        self.firstCharsObjects = {}
        self.firstCharsObjects.update({"level": QGroupBox(title="Уровень")})
        self.firstCharsObjects.update({"experience": QGroupBox(title="Опыт")})
        self.firstCharsObjects.update({"class": QGroupBox(title="Класс")})
        self.firstCharsObjects.update({"race": QGroupBox(title="Раса")})
        self.firstCharsObjects.update({"worldview": QGroupBox(title="Видение мира")})
        self.firstCharsObjects.update({"background": QGroupBox(title="Прошлое")})
        for index, obj in enumerate(self.firstCharsObjects.values()):
            self.firstChars.addWidget(obj, index % 2, index // 2)
        for name, obj in self.firstCharsObjects.items():
            vbox = QVBoxLayout(obj)
            o = {"level": QPushButton, "experience": QPushButton}
            self.firstCharsObjects.update({f"{name}": o.get(name, QLabel)()})
            vbox.addWidget(self.firstCharsObjects[f"{name}"])

        self.firstCharsObjects["level"].clicked.connect(
            lambda: self.changeLevel("level")
        )
        self.firstCharsObjects["experience"].clicked.connect(
            lambda: self.changeLevel("experience")
        )

    def secondCharsInit(self):
        try:
            self.secondChars.removeWidget(self.secondCharsObjects["spells"])
            self.secondChars.removeWidget(self.secondCharsObjects["status"])
            self.secondChars.removeWidget(self.secondCharsObjects["otherButtons"])
        except KeyError:
            pass
        except AttributeError:
            pass
        self.secondCharsObjects = {}
        self.secondCharsObjects.update({"spells": SpellCont(self.character)})
        self.secondCharsObjects.get("spells").sbmChanged.connect(self.needToSend.emit)
        self.secondCharsObjects.update({"status": StatusCont(self.character)})
        self.secondCharsObjects.get("status").sbmChanged.connect(self.needToSend.emit)
        self.secondCharsObjects.update({"otherButtons": QGroupBox()})
        for obj in self.secondCharsObjects.values():
            self.secondChars.addWidget(obj)

    def updateData(self, character):
        self.character = character
        self.mainGroup.setTitle(self.character.name)
        self.levelUPD(self.character.Stats.get("level"))
        self.expUPD(
            self.character.Stats.get("experience"), self.character.getNextLevelExp()
        )
        self.classUPD(self.character.Stats.get("class"))
        self.raceUPD(self.character.Stats.get("race"))
        self.worldviewUPD(self.character.Stats.get("worldview"))
        self.backgroundUPD(self.character.Stats.get("background"))
        self.spellsUPD(self.character)
        self.statusUPD(self.character)

    def levelUPD(self, level):
        self.firstCharsObjects["level"].setText(f"{level}")

    def expUPD(self, exp, nextExp):
        self.firstCharsObjects["experience"].setText(f"{exp}/{nextExp}")

    def classUPD(self, class_name):
        self.firstCharsObjects["class"].setText(f"{class_name}")

    def raceUPD(self, race_name):
        self.firstCharsObjects["race"].setText(f"{race_name}")

    def worldviewUPD(self, worldview):
        self.firstCharsObjects["worldview"].setText(f"{worldview}")

    def backgroundUPD(self, background):
        self.firstCharsObjects["background"].setText(f"{background}")

    def spellsUPD(self, char):
        self.secondCharsObjects.get("spells").setNewCharacter(char)

    def statusUPD(self, char):
        self.secondCharsObjects.get("status").setNewCharacter(char)

    def changeLevel(self, inp):
        if inp == "experience":
            max = self.character.getExpTo20Level()
        else:
            max = 20
        answer = self.changeLevelDialog.getInt(
            self.changeLevelDialog,
            "Change Level",
            f"Enter new {inp}\nup to {max}:",
            self.character.Stats.get(inp),
            1,
            max,
            1,
        )
        if answer[1]:
            self.charLevelUpdate({inp: answer[0]})
