# Form implementation generated from reading ui file 'RawUI/PlayerCard.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import (
    QWidget,
    QGroupBox,
    QHBoxLayout,
    QVBoxLayout,
    QLabel,
    QPushButton,
    QGridLayout,
    QInputDialog,
)


from OtherPyFiles.characterclass import Character
from UI.playerCard.player_card_second_part.secondPart import secondChars


# class Ui_PlayerCard(QWidget):
class Ui_PlayerCard(QWidget):
    needToSend = pyqtSignal(object)
    scratch = {"1": 2, "2": 2, "3": 4, "4": 4, "5": 5, "6": 5}

    def __init__(self, char=Character()):
        super().__init__()
        self.character = char
        self.setupUi()

    def setupUi(self):
        self.initLayout = QVBoxLayout(self)
        self.mainGroup = QGroupBox()
        self.initLayout.addWidget(self.mainGroup)
        self.mainLayout = QVBoxLayout(self.mainGroup)

        self.firstChars = QGridLayout()
        self.firstChars.setContentsMargins(5, 10, 5, 5)
        self.mainLayout.addLayout(self.firstChars)
        self.firstCharsInit()

        self.secondChars = secondChars(self.character)
        self.secondChars.needToSend.connect(self.needToSend.emit)
        self.mainLayout.addWidget(self.secondChars)

        self.changeLevelDialog = QInputDialog(self)
        self.changeExpDialog = QInputDialog(self)

    def charLevelUpdate(self, data):
        self.character.setLevel(data)
        self.needToSend.emit("newLevel&" + str(data))

    def charExpUpdate(self, data):
        self.character.setXp(data)
        self.needToSend.emit("newExp&" + str(data))

    def updateData(self, character):
        self.character = character
        self.NameUPD(self.character.name)
        self.levelUPD(self.character.stats.get("level"))
        self.expUPD(
            self.character.stats.get("experience"), self.character.getNextLevelExp()
        )
        self.classUPD(self.character.stats.get("class"))
        self.raceUPD(self.character.stats.get("race"))
        self.worldviewUPD(self.character.stats.get("worldview"))
        self.backgroundUPD(self.character.stats.get("background"))
        self.spellsUPD()
        self.statusUPD()
        self.buttonsUPD()

    def firstCharsInit(self):
        self.firstCharsObjects = {}
        self.firstCharsObjects.update({"level": QGroupBox(title="Уровень")})
        self.firstCharsObjects.update({"experience": QGroupBox(title="Опыт")})
        self.firstCharsObjects.update({"class": QGroupBox(title="Класс")})
        self.firstCharsObjects.update({"race": QGroupBox(title="Раса")})
        self.firstCharsObjects.update({"worldview": QGroupBox(title="Видение мира")})
        self.firstCharsObjects.update({"background": QGroupBox(title="Прошлое")})
        for index, obj in enumerate(self.firstCharsObjects.values()):
            self.firstChars.addWidget(obj, index % 2, index // 2)
        for name, obj in self.firstCharsObjects.items():
            vbox = QVBoxLayout(obj)
            o = {"level": QPushButton, "experience": QPushButton}
            self.firstCharsObjects.update({f"{name}": o.get(name, QLabel)()})
            vbox.addWidget(self.firstCharsObjects[f"{name}"])

        self.firstCharsObjects["level"].clicked.connect(self.changeLevel)
        self.firstCharsObjects["experience"].clicked.connect(self.changeExp)

    def NameUPD(self, name):
        self.character.name = name
        hpInfo = self.character.stats.get("health", {})
        print(hpInfo)
        string = str(hpInfo.get("main", {}).get("val", 1))
        if hpInfo.get("temp", 0):
            string += f" [+{hpInfo.get('temp', 0)}]"
        string += f"/{hpInfo.get('main', {}).get('max', 1)}"
        self.mainGroup.setTitle(f"{name} ({string})")

    def levelUPD(self, level):
        self.firstCharsObjects["level"].setText(f"{level}")

    def expUPD(self, exp, nextExp):
        self.firstCharsObjects["experience"].setText(f"{exp}/{nextExp}")

    def classUPD(self, class_name):
        self.firstCharsObjects["class"].setText(f"{class_name}")

    def raceUPD(self, race_name):
        self.firstCharsObjects["race"].setText(f"{race_name}")

    def worldviewUPD(self, worldview):
        self.firstCharsObjects["worldview"].setText(f"{worldview}")

    def backgroundUPD(self, background):
        self.firstCharsObjects["background"].setText(f"{background}")

    def spellsUPD(self):
        print("updating spells", self.character.spellCells)
        self.secondChars.cells_container.characterUpdate(self.character)

    def statusUPD(self):
        print("updating status", self.character.status)
        self.secondChars.second_horizontal_part.statuses_container.characterUpdate(
            self.character
        )

    def buttonsUPD(self):
        print(self.character.stats.get("diceStats"))
        self.secondChars.second_horizontal_part.addict_button_part.characterUpdate(
            self.character
        )

    def changeLevel(self, inp):
        max = 20
        answer = self.changeLevelDialog.getInt(
            self.changeLevelDialog,
            "Change Level",
            f"Enter new {inp}\nup to {max}:",
            self.character.stats.get("level"),
            1,
            max,
            1,
        )
        if answer[1]:
            self.charLevelUpdate(answer[0])

    def changeExp(self):
        max = self.character.getExpTo20Level()
        answer = self.changeExpDialog.getInt(
            self.changeExpDialog,
            "Change Experience",
            f"Enter new experience\nup to {max}:",
            self.character.stats.get("experience"),
            0,
            max,
            1,
        )
        if answer[1]:
            self.charExpUpdate(answer[0])
