# Form implementation generated from reading ui file 'RawUI/CharacterCreate.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtCore import QRect, Qt
from PyQt6.QtWidgets import QWidget, QVBoxLayout, QPushButton, QTabWidget

from OtherPyFiles.characterclass import Character

from UI.CreateChar.FirstCharacteristics import FirstCharacteristics as FirstChar
from UI.CreateChar.SecondCharacteristics import SecondCharacteristics as SecondChar
from UI.CreateChar.ThirdCharacteristics import ThirdCharacteristics as ThirdChar
from UI.CreateChar.HealthCharacteristics import HealthCharacteristics as HealthChar
from UI.CreateChar.InventoryCharacteristics import InventoryCharacteristics as InvChar


class Ui_MainList(QWidget):
    def __init__(self):
        super().__init__()
        self.character = Character()
        self.setupUi()

    def setupUi(self):
        self.resize(720, 540)
        self.setGeometry(QRect(0, 0, 720, 540))

        self.ScreenManager = QVBoxLayout(self)

        self.BackButton = QPushButton(text="Назад")
        self.ScreenManager.addWidget(self.BackButton, 1, Qt.AlignmentFlag.AlignHCenter)

        self.Characteristics = QTabWidget()
        self.setStyleSheet("""
            QTabWidget::tab-bar {
                alignment: center;
            }
        """)
        self.ScreenManager.addWidget(self.Characteristics)
        self.firstCharacteristicsInit()
        self.secondCharacteristicsInit()
        self.thirdCharacteristicsInit()
        self.healthCharacteristicsInit()
        self.inventoryCharacteristicsInit()

        self.Characteristics.setCurrentIndex(0)

    def class_changed(self):
        print("classCh")
        self.HealthChar.classUpd(
            self.character, self.ThirdChar.diceObjects.get("Телосложение")
        )

    def level_changed(self, level):
        print(level)
        print(self.Characteristics.indexOf(self.HealthChar))
        if level > 1:
            self.Characteristics.insertTab(3, self.HealthChar, "Здоровье")
            self.HealthChar.varUpd(
                self.character, self.ThirdChar.diceObjects.get("Телосложение")
            )
        else:
            try:
                self.Characteristics.removeTab(
                    self.Characteristics.indexOf(self.HealthChar)
                )
                self.healthCharacteristicsInit()
            except:
                pass

    def firstCharacteristicsInit(self):
        self.FirstChar = FirstChar(self.character)
        self.FirstChar.LevelSelectBox.valueChanged.connect(self.level_changed)
        self.Characteristics.addTab(self.FirstChar, "Имя")

    def secondCharacteristicsInit(self):
        self.SecondChar = SecondChar(self.character)
        self.SecondChar.classChoose.currentTextChanged.connect(self.class_changed)
        self.Characteristics.addTab(self.SecondChar, "Раса и Класс")

    def thirdCharacteristicsInit(self):
        self.ThirdChar = ThirdChar(self.character)
        self.Characteristics.addTab(self.ThirdChar, "Параметры")

    def healthCharacteristicsInit(self):
        self.HealthChar = HealthChar(
            self.character, self.ThirdChar.diceObjects.get("Телосложение")
        )

    def inventoryCharacteristicsInit(self):
        self.InvChar = InvChar(self.character)
        self.Characteristics.addTab(self.InvChar, "Инвентарь")
