# Form implementation generated from reading ui file 'RawUI/CharacterCreate.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRect, QSize, Qt
from PyQt6.QtWidgets import *

from characterclass import *

from UI.CreateChar.FirstCharacteristics import FirstCharacteristics as FirstChar
from UI.CreateChar.SecondCharacteristics import SecondCharacteristics as SecondChar
from UI.CreateChar.ThirdCharacteristics import ThirdCharacteristics as ThirdChar

class Ui_MainList(QWidget):
    def __init__(self):
        super().__init__()
        self.character = Character()
        self.setupUi()
    def setupUi(self):
        self.resize(720, 540)
        self.setGeometry(QRect(0,0,720,540))

        self.ScreenManager = QVBoxLayout(self)

        self.BackButton = QPushButton(text="Назад")
        self.ScreenManager.addWidget(self.BackButton)

        self.Characteristics = QtWidgets.QTabWidget()
        self.setStyleSheet('''
            QTabWidget::tab-bar {
                alignment: center;
            }
        ''')
        self.ScreenManager.addWidget(self.Characteristics)
        self.firstCharacteristicsInit()
        self.secondCharacteristicsInit()
        self.thirdCharacteristicsInit()

        self.Characteristics.setCurrentIndex(0)

    def firstCharacteristicsInit(self):
        self.FirstChar = FirstChar(self.character)
        self.Characteristics.addTab(self.FirstChar, "Имя")

    def secondCharacteristicsInit(self):
        self.SecondChar = SecondChar(self.character)
        self.Characteristics.addTab(self.SecondChar,"Раса и Класс")

        

    def thirdCharacteristicsInit(self):
        self.ThirdChar = ThirdChar(self.character)
        self.Characteristics.addTab(self.ThirdChar,"Параметры")


