# Form implementation generated from reading ui file 'RawUI/CharactersList.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtCore import QRect, Qt, pyqtSignal
from PyQt6.QtWidgets import (
    QListWidget,
    QPushButton,
    QVBoxLayout,
    QHBoxLayout,
    QWidget,
)

from OtherPyFiles.characterclass import Character, CharLoader
from UI.characterMainChars import CharMainChar


class Ui_CharsList(QWidget):
    def __init__(self, client):
        super().__init__()
        self.ClientOBJ = client
        self.currCharacter = Character()
        self.Opts = {}
        self.setupUi()

    def setupUi(self):
        self.mainLayout = QHBoxLayout(self)
        self.mainLayout.setContentsMargins(20, 8, 20, 8)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)

        self.choose = QVBoxLayout()
        self.mainLayout.addLayout(self.choose, 2)

        self.BackButton = QPushButton("Назад")
        self.choose.addWidget(self.BackButton)

        self.CharactersList = QListWidget()
        self.CharactersList.currentTextChanged.connect(self.characterSelected)
        self.choose.addWidget(self.CharactersList)

        self.charButtons = QHBoxLayout()
        self.charButtons.setSpacing(5)
        self.createNewButton = QPushButton("Создать нового")
        self.charButtons.addWidget(self.createNewButton, 6)

        self.deleteCharacterButton = QPushButton("Удалить")
        self.deleteCharacterButton.clicked.connect(self.deleteCharacter)
        self.charButtons.addWidget(self.deleteCharacterButton, 2)

        self.choose.addLayout(self.charButtons, 1)

        self.characterOpts = CharMainChar()
        self.mainLayout.addWidget(self.characterOpts, 3)

    def charsInit(self):
        cI = CharLoader().CharClassDispencer()
        print(cI)
        return cI

    def characterFind(self):
        self.allChars = self.charsInit()
        self.CharactersList.clear()
        for char in self.allChars.values():
            self.CharactersList.addItem(char.name)

    def deleteCharacter(self):
        selected = self.CharactersList.currentItem()
        if selected:
            name = selected.text()
            if name in self.allChars:
                self.allChars[name].jsonCharDelete()
                self.characterFind()

    def characterSelected(self, name):
        if name:
            print(name, self.allChars[name].Stats)
            self.currCharacter = self.allChars[name]
            self.characterOpts.showNewCharacter(self.allChars.get(name, Character()))
