# Form implementation generated from reading ui file 'RawUI/CharactersList.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal, Qt
from PyQt6.QtWidgets import QWidget, QPushButton
from characterclass import Character, CharLoader, jsonLoad


class Ui_CharsList(QWidget):
    def __init__(self,client):
        super().__init__()
        self.ClientOBJ = client
        self.currCharacter = Character()
        self.Opts = {}
        self.allChars = CharLoader().CharClassDispencer()
        self.characterSelected = pyqtSignal(object)
        self.setupUi()
    
    def setupUi(self):
        self.setObjectName("Main")
        self.resize(720, 540)
        self.setGeometry(QtCore.QRect(0,0,720,540))
        
        self.Panels = QtWidgets.QGridLayout(self)

        self.BackButton = QtWidgets.QPushButton(text="Назад")
        self.Panels.addWidget(self.BackButton,0,0,Qt.AlignmentFlag.AlignHCenter)

        self.CharactersList = QtWidgets.QListWidget()
        self.CharactersList.currentItemChanged.connect(self.characterChange)
        self.Panels.addWidget(self.CharactersList,1,0)

        self.CreateNewCharButton = QtWidgets.QPushButton(text="Создать нового")
        self.Panels.addWidget(self.CreateNewCharButton,2,0,Qt.AlignmentFlag.AlignHCenter)

        self.CharacterOpts = QtWidgets.QWidget()
        self.CharacterOptsLayout = QtWidgets.QVBoxLayout(self.CharacterOpts)
        OptsSizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,QtWidgets.QSizePolicy.Policy.Expanding)
        OptsSizePolicy.setHorizontalStretch(2)
        self.CharacterOpts.setSizePolicy(OptsSizePolicy)
        self.characterOptsInit(self.CharacterOptsLayout)
        self.Panels.addWidget(self.CharacterOpts,1,1)


        self.characterFind(self.CharactersList)
    def characterChange(self,index:QtWidgets.QListWidgetItem):
        index = index.text()
        self.currCharacter = self.allChars.get(index)
        self.updatesShow()
        self.select(self.currCharacter)

    def characterFind(self,listObject : QtWidgets.QListWidget):
        listObject.clear()
        for character in self.allChars:
            listObject.addItem(character)
    def characterOptsInit(self,listObject: QtWidgets.QVBoxLayout):
        opts = ["name","level","experience","class","race","worldview","background","skills","diceStats"]
        for opt in opts:
            self.Opts[opt] = QtWidgets.QLabel()
            self.Opts[opt].setWordWrap(True)
            listObject.addWidget(self.Opts[opt])

    def updatesShow(self):
        _char = self.currCharacter
        self.Opts.get("name").setText(_char.name)
        for _title,_text in _char.Stats.items():
            self.Opts.get(_title,QtWidgets.QLabel()).setText(str(_text))
    

    def select(self,char):
        self.ClientOBJ.character = char

