# Form implementation generated from reading ui file 'RawUI/CharactersList.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtCore import QRect, Qt, pyqtSignal
from PyQt6.QtWidgets import (
    QGridLayout,
    QListWidget,
    QListWidgetItem,
    QPushButton,
    QScrollArea,
    QTreeWidget,
    QTreeWidgetItem,
    QVBoxLayout,
    QWidget,
)

from OtherPyFiles.characterclass import Character, CharLoader


class Ui_CharsList(QWidget):
    def __init__(self, client):
        super().__init__()
        self.ClientOBJ = client
        self.currCharacter = Character()
        self.Opts = {}
        self.characterSelected = pyqtSignal(object)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Main")
        self.resize(720, 540)
        self.setGeometry(QRect(0, 0, 720, 540))

        self.Panels = QGridLayout(self)

        self.BackButton = QPushButton(text="Назад")
        self.Panels.addWidget(self.BackButton, 0, 0, Qt.AlignmentFlag.AlignHCenter)

        self.CharactersList = QListWidget()
        self.CharactersList.currentItemChanged.connect(self.characterChange)
        self.Panels.addWidget(self.CharactersList, 1, 0)

        self.CreateNewCharButton = QPushButton(text="Создать нового")
        self.Panels.addWidget(
            self.CreateNewCharButton, 2, 0, Qt.AlignmentFlag.AlignHCenter
        )

        self.CharacterOpts = QScrollArea()
        self.CharacterOptsLayout = QVBoxLayout(self.CharacterOpts)
        self.CharacterOptsTree = TreeWidget()
        self.CharacterOptsTree.setHeaderLabel("Персонаж")
        self.CharacterOptsLayout.addWidget(self.CharacterOptsTree)

        # self.CharacterOptsTitle = QTreeWidgetItem(self.CharacterOptsTree,[self.currCharacter.name])
        self.CharacterOptsTree.recursiveAddTreeItems(
            self.CharacterOptsTree, self.currCharacter.Stats
        )
        self.Panels.addWidget(self.CharacterOpts, 1, 1)

        self.characterFind(self.CharactersList)

    def characterChange(self, index: QListWidgetItem):
        if not index:
            return
        index = index.text()
        self.currCharacter = self.allChars.get(index)
        self.updatesShow()
        self.select(self.currCharacter)

    def characterFind(self, listObject: QListWidget = None):
        if listObject is None:
            listObject = self.CharactersList
        self.allChars = CharLoader().CharClassDispencer()
        listObject.clear()
        for character in self.allChars:
            listObject.addItem(character)

    def updatesShow(self):
        self.CharacterOptsTree.clear()
        self.CharacterOptsTree.setHeaderLabel(self.currCharacter.name)
        # self.CharacterOptsTitle = QTreeWidgetItem(self.CharacterOptsTree,[self.currCharacter.name])
        self.CharacterOptsTree.recursiveAddTreeItems(
            self.CharacterOptsTree, self.currCharacter.Stats
        )
        self.CharacterOptsTree.expandAll()

    def select(self, char):
        self.ClientOBJ.character = char


class TreeWidget(QTreeWidget):
    def recursiveAddTreeItems(
        self, parent: QTreeWidgetItem, value: str | int | dict | list, _dict={}
    ):
        if type(value) == type(1):
            value = str(value)
        if type(value) == type(list()):
            for _val in value:
                _dict[_val] = QTreeWidgetItem(parent, [_val])
        if type(value) == type(dict()):
            for _key, _val in value.items():
                _dict[_key] = QTreeWidgetItem(parent, [_key])
                _dict[_key].setHidden(False)
                _dict[_key + "_"] = self.recursiveAddTreeItems(_dict[_key], _val, _dict)
        if type(value) == type(str()):
            _dict[value] = QTreeWidgetItem(parent, [value])
        return _dict
