# Form implementation generated from reading ui file 'RawUI/ClientLobby.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QVBoxLayout, QWidget, QStackedWidget
from OtherPyFiles.server_client import dataSize
from UI.playerCard.PlayerCard import Ui_PlayerCard
from UI.CharactersList import Ui_CharsList


class Ui_Lobby(QWidget):
    def __init__(self, client):
        super().__init__()
        self.ClientOBJ = client
        self.setupUi()

    def setupUi(self):
        self.vbox = QVBoxLayout(self)
        self.stackedWidget = QStackedWidget(self)
        self.vbox.addWidget(self.stackedWidget)

        self.CharSelect = Ui_CharsList(self.ClientOBJ)

        self.CharSelect.CharactersList.doubleClicked.connect(self.showCard)
        self.stackedWidget.addWidget(self.CharSelect)
        self.Card = Ui_PlayerCard(char=self.ClientOBJ.character, client=self.ClientOBJ)
        self.ClientOBJ.data_updated.connect(self.Card.updateData)
        self.Card.needToSend.connect(self.send)
        self.stackedWidget.addWidget(self.Card)
        self.stackedWidget.setCurrentWidget(self.CharSelect)

    def send(self, dataToSend):
        print("Sending data:", dataToSend)
        print(self.ClientOBJ.character.status)
        if dataToSend:
            self.ClientOBJ.sendToServer(*dataToSend)

            match dataToSend[0]:
                case ["newLevel", l]:
                    if l != -1:
                        self.Card.updateData(self.ClientOBJ.character)

            return
        self.ClientOBJ.sendToServer(
            ["newStats", self.ClientOBJ.character.stats],
            ["newSpellCells", self.ClientOBJ.character.spellCells],
            ["newStatus", self.ClientOBJ.character.status],
        )
        self.Card.updateData(self.ClientOBJ.character)

    def showCard(self):
        self.ClientOBJ.character = self.CharSelect.currCharacter
        self.stackedWidget.setCurrentIndex(1)
        self.ClientOBJ.sendToServer(
            ["characterNameChanged", self.ClientOBJ.character.name]
        )
        self.send(None)
