# Form implementation generated from reading ui file 'RawUI/ClientLobby.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget, QVBoxLayout
from UI.PlayerCard import Ui_PlayerCard
from UI.CharactersList import Ui_CharsList

class Ui_Lobby(QWidget):
    def __init__(self,client):
        super().__init__()
        self.ClientOBJ = client
        self.setupUi()

    def setupUi(self):
        self.stackedWidget = QtWidgets.QStackedWidget(self)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 680, 520))
        self.stackedWidget.setObjectName("stackedWidget")

        self.CharSelect = Ui_CharsList(self.ClientOBJ)
        
        self.stackedWidget.addWidget(self.CharSelect)
        
        print(self.ClientOBJ.character)
        self.Card = Ui_PlayerCard()
        self.stackedWidget.addWidget(self.Card)
        if self.ClientOBJ.character.name == "Выбирается":
            self.stackedWidget.setCurrentIndex(0)
            self.CharSelect.SelectButton.clicked.connect(self.showCard)
        else: self.showCard()

    def showCard(self):
        self.stackedWidget.setCurrentIndex(1)
        self.Card.updateData(self.ClientOBJ.character)
        self.ClientOBJ.sendToServer("characterNameChanged", self.ClientOBJ.character.name)
        self.ClientOBJ.sendToServer("newData", self.ClientOBJ.character.Stats,self.ClientOBJ.character.spellCells, self.ClientOBJ.character.status)
        

