# Form implementation generated from reading ui file 'RawUI/CharacterCreate.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRect, QSize, Qt
from PyQt6.QtWidgets import *

from characterclass import *

class Ui_MainList(QWidget):
    def __init__(self):
        super().__init__()
        self.character = Character()
        self.setupUi()
    def setupUi(self):
        self.resize(720, 540)
        self.setGeometry(QRect(0,0,720,540))

        self.ScreenManager = QVBoxLayout(self)

        self.BackButton = QPushButton(text="Назад")
        self.ScreenManager.addWidget(self.BackButton)

        self.Characteristics = QtWidgets.QTabWidget()
        self.setStyleSheet('''
            QTabWidget::tab-bar {
                alignment: center;
            }
        ''')
        self.ScreenManager.addWidget(self.Characteristics)
        self.firstCharacteristicsInit()
    def firstCharacteristicsInit(self):
        self.FirstChar = QtWidgets.QWidget()

        self.verticalLayout = QtWidgets.QVBoxLayout(self.FirstChar)

        self.Trash = QtWidgets.QLabel(text="В этом меню можно создать нового персонажа, который будет учавствовать в приключениях, придуманных вашим гейммастером")
        self.Trash.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Trash.setWordWrap(True)
        self.verticalLayout.addWidget(self.Trash,2)

        self.PlayerNameTitle = QtWidgets.QLabel(text="Имя вашего персонажа\n|\n\/")
        self.PlayerNameTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout.addWidget(self.PlayerNameTitle)

        self.NameInput = QtWidgets.QLineEdit()
        self.NameInput.textChanged.connect(self.on_name_changed)
        self.NameInput.setPlaceholderText("Имя")
        self.verticalLayout.addWidget(self.NameInput, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.label = QtWidgets.QLabel()
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout.addWidget(self.label)

        self.horizontalLayout = QtWidgets.QHBoxLayout()

        self.LevelBox = QtWidgets.QGroupBox(title="Уровень")
        self.levelvbox = QVBoxLayout(self.LevelBox)
        self.levelRange = QLabel(text="Введите уровень от 1 до 20")
        self.levelvbox.addWidget(self.levelRange)
        self.LevelSelectBox = QtWidgets.QSpinBox()
        self.levelvbox.addWidget(self.LevelSelectBox)
        self.LevelSelectBox.setValue(1)
        self.LevelSelectBox.setMinimum(1)
        self.LevelSelectBox.setMaximum(20)
        self.LevelSelectBox.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.LevelSelectBox.valueChanged.connect(self.on_level_changed)
        self.horizontalLayout.addWidget(self.LevelBox)

        self.expBox = QtWidgets.QGroupBox(title="Опыт")
        self.expvbox = QVBoxLayout(self.expBox)
        self.expRange = QLabel()
        self.expvbox.addWidget(self.expRange)
        self.expSelectBox = QtWidgets.QSpinBox(self.expBox)
        self.expvbox.addWidget(self.expSelectBox)
        self.expSelectBox.setValue(0)
        self.expSelectBox.setMinimum(0)
        self.expSelectBox.valueChanged.connect(self.on_exp_changed)
        self.horizontalLayout.addWidget(self.expBox)
        self.expMan(self.LevelSelectBox.value())

        self.verticalLayout.addLayout(self.horizontalLayout,1)

        self.Characteristics.addTab(self.FirstChar, "Имя")

        self.Characteristics.setCurrentIndex(0)
    
    def secondCharacteristicsInit(self):
        self.SecondChar = QWidget()
        self.Characteristics.addTab(self.SecondChar,"Раса и Класс")

        self.mainLayout = QHBoxLayout(self.SecondChar)

        self.classLayout = QVBoxLayout()

        self.classTitle = QLabel(text="Выберите класс вашего персонажа")
        self.classLayout.addWidget(self.classTitle,2)

        self.classChoose = QComboBox()
        self.comboAdder(self.classChoose,"JSONS/dnd_classes.json")

    def on_name_changed(self,text):
        width = self.NameInput.fontMetrics().horizontalAdvance(text) + 20
        self.NameInput.setMinimumWidth(width)
        self.character.setName(text)
        print(self.character.name,self.character.Stats)

    def on_level_changed(self,level):
        self.expMan(level)
        self.character.setLevel(level)
        print(self.character.name,self.character.Stats)

    def on_exp_changed(self,exp):
        self.character.setXp(exp)
        print(self.character.name,self.character.Stats)

    def expMan(self,_level):
        _maxXp = jsonLoad("JSONS/dnd_levels.json").get(str(_level+1),1).get("experience",0) - 1
        self.expRange.setText(f"Введите опыт от 0 до {_maxXp}")
        self.expSelectBox.setMaximum(_maxXp)
    def comboAdder(self,obj : QComboBox,path: str):
        classesInfo = jsonLoad(path)
        for className in classesInfo:
            obj.addItem(className) 
            

