# Form implementation generated from reading ui file 'RawUI/LevelChanger.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self,level = 1,exp = 0,maxExp = 300):
        super().__init__()
        self.level = level
        self.exp = exp
        self.maxExp = maxExp
    def dataUpdate(self,level,exp,maxExp):
        self.level = level
        self.exp = exp
        self.maxExp = maxExp
        self.dataShow()

    def dataShow(self):
        self.LevelName.setText(str(self.level))
        self.EXPSwap.setProperty("value", self.exp)
        self.EXPSwap.setProperty("maximum", 42424242)
        self.ProgressBar.setProperty("value", self.exp)
        self.ProgressBar.setProperty("maximum", self.maxExp)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 254, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalWidget.setGeometry(QtCore.QRect(10, 10, 381, 231))
        self.verticalWidget.setObjectName("verticalWidget")
        self.dialoglayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.dialoglayout.setContentsMargins(0, 0, 0, 0)
        self.dialoglayout.setObjectName("dialoglayout")
        self.LevelWidget = QtWidgets.QWidget(parent=self.verticalWidget)
        self.LevelWidget.setObjectName("LevelWidget")
        self.levellayout = QtWidgets.QHBoxLayout(self.LevelWidget)
        self.levellayout.setContentsMargins(28, -1, -1, -1)
        self.levellayout.setSpacing(28)
        self.levellayout.setObjectName("levellayout")
        self.LevelName = QtWidgets.QLabel(parent=self.LevelWidget)
        self.LevelName.setMaximumSize(QtCore.QSize(85, 85))
        self.LevelName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LevelName.setObjectName("LevelName")
        self.levellayout.addWidget(self.LevelName)
        self.LevSwapWidget = QtWidgets.QWidget(parent=self.LevelWidget)
        self.LevSwapWidget.setObjectName("LevSwapWidget")
        self.levelswap = QtWidgets.QVBoxLayout(self.LevSwapWidget)
        self.levelswap.setObjectName("levelswap")
        self.levelup = QtWidgets.QPushButton(parent=self.LevSwapWidget)
        self.levelup.setMaximumSize(QtCore.QSize(200, 16777215))
        self.levelup.setObjectName("levelup")
        self.levelup.clicked.connect(lambda: self.dataUpdate(self.level+1,0,300))
        self.levelswap.addWidget(self.levelup)
        self.leveldown = QtWidgets.QPushButton(parent=self.LevSwapWidget)
        self.leveldown.setMaximumSize(QtCore.QSize(200, 16777215))
        self.leveldown.setObjectName("leveldown")
        self.leveldown.clicked.connect(lambda: self.dataUpdate(self.level-1,0,300))
        self.levelswap.addWidget(self.leveldown)
        self.levellayout.addWidget(self.LevSwapWidget)
        self.dialoglayout.addWidget(self.LevelWidget)
        self.EXPWidget = QtWidgets.QWidget(parent=self.verticalWidget)
        self.EXPWidget.setObjectName("EXPWidget")
        self.explayout = QtWidgets.QHBoxLayout(self.EXPWidget)
        self.explayout.setObjectName("explayout")
        self.EXPSwap = QtWidgets.QSpinBox(parent=self.EXPWidget)
        self.EXPSwap.setObjectName("EXPSwap")
        self.EXPSwap.valueChanged.connect(lambda : self.dataUpdate(self.level,self.EXPSwap.value(),self.maxExp))
        self.explayout.addWidget(self.EXPSwap)
        self.dialoglayout.addWidget(self.EXPWidget)
        self.ProgressBar = QtWidgets.QProgressBar(parent=self.verticalWidget)
        self.ProgressBar.setObjectName("ProgressBar")
        self.dialoglayout.addWidget(self.ProgressBar)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.levelup.setText(_translate("Dialog", "Увеличить"))
        self.leveldown.setText(_translate("Dialog", "Уменьшить"))
        self.EXPSwap.setSuffix(_translate("Dialog", " опыта"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
