# Form implementation generated from reading ui file 'RawUI/PlayerCard.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget, QFrame, QDialog
from UI.SpellCellsObj import Ui_SpellCellObj
from UI.LevelChanger import Ui_Dialog
from characterclass import Character

#class Ui_PlayerCard(QWidget):
class Ui_PlayerCard(QtWidgets.QFrame):
    needToSend = QtCore.pyqtSignal()
    def __init__(self, char=Character(),client = None):
        super().__init__()
        self.character = char
        self.spellLines = []
        self.setupUi()
        self.showUpdates()
    
    def updateData(self, character):
        self.character = character
        self.showUpdates()
        self.spellsUpdate()
        self.statusUpdate()
        self.retranslateUi()
    
    def showUpdates(self):
        self.NameText.setText(self.character.name)
        if self.character.name == "Выбирается":
            return
        self.LevelText.setText(str(self.character.Stats.get('level', '')))
        exp = self.character.Stats.get('experience', '')
        self.ExpText.setText(f"{exp} / {self.character.maxExp}")
        self.ClassText.setText(self.character.Stats.get('class', ''))
        self.RaceText.setText(self.character.Stats.get('race', ''))
        self.WVText.setText(self.character.Stats.get('worldview', ''))
        self.BGText.setText(self.character.Stats.get('background', ''))

    def spellsUpdate(self):
        for i in range(self.AllCellsLayout.count()):
            self.AllCellsLayout.itemAt(i).widget().deleteLater()
        try:
            for name,count in self.character.spellCells.items():
                try:
                    maxCellsCount:str = self.character.Stats.get("otherStats").get("MaxspellCells",self.character.Stats.get("otherStats").get("Ячейки заклинаний")).get(str(name))
                except AttributeError:
                    try: maxCellsCount:str = self.character.Stats.get("otherStats").get("MaxspellCells",self.character.Stats.get("otherStats").get("Ячейки заклинаний"))
                    except:
                        maxCellsCount = 0
                maxCellsCount = int(maxCellsCount)
                line = Ui_SpellCellObj(str(name),int(count),maxCellsCount)
                line.changedSignal.connect(self.spellCellsChange)
                self.AllCellsLayout.addWidget(line)
                self.spellLines.append(line)
        except RuntimeError:
            pass
    def spellCellsChange(self, data:str):
        data = data.split("$")
        self.character.spellCellsCh(data[0],data[1])
        self.updateData(self.character)
        self.needToSend.emit()
    def levelChange(self):
        lev = self.LevelDialog.level
        ex = self.LevelDialog.exp
        self.character.setLevel(lev)
        self.character.setXp(ex)
        print(self.character.Stats.get("level")," - ",self.character.Stats.get("experience"), " - ", self.character.maxExp)
        self.updateData(self.character)
        self.needToSend.emit()
    def statusUpdate(self):
        pass

    def setupSecondary(self):
        self.secondaryWidget = QtWidgets.QWidget(self)
        self.secondaryWidget.setGeometry(QtCore.QRect(10,110,700,351))
        self.secondaryInfo = QtWidgets.QHBoxLayout(self.secondaryWidget)
        self.SpellCells = QtWidgets.QGroupBox()
        self.SpellCells.setGeometry(QtCore.QRect(10, 110, 200, 351))
        self.SpellCells.setObjectName("SpellCells")
        self.secondaryInfo.addWidget(self.SpellCells)
        self.AllCells = QtWidgets.QFrame(parent=self.SpellCells)
        self.AllCells.setGeometry(QtCore.QRect(15, 35, 170, 301))
        self.AllCells.setMinimumSize(QtCore.QSize(0, 0))
        self.AllCells.setStyleSheet("background-color: rgb(124, 124, 124);")
        self.AllCells.setObjectName("AllCells")
        self.AllCellsLayout = QtWidgets.QVBoxLayout(self.AllCells)
        self.AllCellsLayout.setSpacing(2)
        self.AllCellsLayout.setObjectName("AllCellsLayout")


        self.StatusData = QtWidgets.QGroupBox()
        self.StatusData.setGeometry(QtCore.QRect(220, 110, 300, 351))
        self.StatusData.setObjectName("StatusData")
        self.secondaryInfo.addWidget(self.StatusData)
        
        self.buttonsWidget = QtWidgets.QWidget()
        self.buttonsLayout = QtWidgets.QVBoxLayout(self.buttonsWidget)
        buttonSize = QtCore.QSize(80,60)
        self.buttonsLayout.setSpacing(6)
        self.healthButton = QtWidgets.QPushButton(parent=self)
        self.healthButton.setMinimumSize(buttonSize)
        self.healthButton.setObjectName("healthButton")
        self.buttonsLayout.addWidget(self.healthButton)
        self.dicesButton = QtWidgets.QPushButton(parent=self)
        self.dicesButton.setMinimumSize(buttonSize)
        self.dicesButton.setObjectName("dicesButton")
        self.buttonsLayout.addWidget(self.dicesButton)
        self.invButton = QtWidgets.QPushButton(parent=self)
        self.invButton.setMinimumSize(buttonSize)
        self.invButton.setObjectName("invButton")
        self.buttonsLayout.addWidget(self.invButton)
        self.spellsButton = QtWidgets.QPushButton(parent=self)
        self.spellsButton.setMinimumSize(buttonSize)
        self.spellsButton.setObjectName("spellsButton")
        self.buttonsLayout.addWidget(self.spellsButton)

        

        self.secondaryInfo.addWidget(self.buttonsWidget)
    def levelChangeOpen(self):
        self.LevelDialog.dataUpdate(self.character.Stats.get("level"),self.character.Stats.get("experience"),self.character.maxExp)
        self.LevelDialogMenu.show()
        self.LevelDialogMenu.accepted.connect(self.levelChange)
    def setupUi(self):
        self.setGeometry(QtCore.QRect(0,0,720,540))
        self.layoutWidget = QtWidgets.QWidget(parent=self)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 700, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.PrimaryInfo = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.PrimaryInfo.setContentsMargins(0, 0, 0, 0)
        self.PrimaryInfo.setSpacing(5)
        self.PrimaryInfo.setObjectName("PrimaryInfo")
        self.NameArea = QtWidgets.QFrame(parent=self.layoutWidget)
        self.NameArea.setMinimumSize(QtCore.QSize(340,85))
        self.NameArea.setMaximumSize(QtCore.QSize(16777215, 85))
        self.NameArea.setStyleSheet("background-color: rgb(42, 42, 42);")
        self.NameArea.setObjectName("NameArea")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.NameArea)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NameText = QtWidgets.QLabel(parent=self.NameArea)
        self.NameText.setMaximumSize(QtCore.QSize(16777215, 60))
        self.NameText.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.NameText.setWordWrap(True)
        self.NameText.setObjectName("NameText")
        self.horizontalLayout.addWidget(self.NameText)
        self.LevelData = QtWidgets.QVBoxLayout()
        self.LevelData.setObjectName("LevelData")
        self.LevelText = QtWidgets.QPushButton(parent=self.NameArea)
        self.LevelText.setMinimumSize(QtCore.QSize(0, 42))
        self.LevelText.setMaximumSize(QtCore.QSize(85, 16777215))
        self.LevelText.setObjectName("LevelText")
        self.LevelDialogMenu = QDialog()
        self.LevelDialog = Ui_Dialog()
        self.LevelDialog.setupUi(self.LevelDialogMenu)
        self.LevelText.clicked.connect(self.levelChangeOpen)
        self.LevelData.addWidget(self.LevelText)
        self.ExpText = QtWidgets.QLabel(parent=self.NameArea)
        self.ExpText.setStyleSheet("font-size: 13pt;")
        self.ExpText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ExpText.setObjectName("ExpText")
        self.LevelData.addWidget(self.ExpText)
        self.horizontalLayout.addLayout(self.LevelData)
        self.PrimaryInfo.addWidget(self.NameArea)
        self.MainChars = QtWidgets.QFrame(parent=self.layoutWidget)
        self.MainChars.setStyleSheet("background-color: rgb(85, 85, 85); font-size: 18px;")
        self.MainChars.setMinimumSize(355,100)
        self.MainChars.setMaximumSize(355,100)
        self.MainChars.setObjectName("MainChars")
        self.layoutChars = QtWidgets.QGridLayout(self.MainChars)
        self.layoutChars.setObjectName("layoutChars")
        self.BGText = QtWidgets.QLabel(parent=self.MainChars)
        self.BGText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BGText.setWordWrap(True)
        self.BGText.setObjectName("BGText")
        self.layoutChars.addWidget(self.BGText, 1, 1, 1, 1)
        self.RaceText = QtWidgets.QLabel(parent=self.MainChars)
        self.RaceText.setStyleSheet("")
        self.RaceText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.RaceText.setObjectName("RaceText")
        self.layoutChars.addWidget(self.RaceText, 0, 1, 1, 1)
        self.ClassText = QtWidgets.QLabel(parent=self.MainChars)
        self.ClassText.setStyleSheet("")
        self.ClassText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ClassText.setObjectName("ClassText")
        self.layoutChars.addWidget(self.ClassText, 0, 0, 1, 1)
        self.WVText = QtWidgets.QLabel(parent=self.MainChars)
        self.WVText.setStyleSheet("")
        self.WVText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.WVText.setWordWrap(True)
        self.WVText.setObjectName("WVText")
        self.layoutChars.addWidget(self.WVText, 1, 0, 1, 1)
        self.PrimaryInfo.addWidget(self.MainChars)
        self.setupSecondary()
        self.updateData(self.character)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.SpellCells.setTitle("Ячейки заклинаний")
        self.StatusData.setTitle("Статус")
        self.healthButton.setText(_translate("PlayerCard", "Здоровье"))
        self.dicesButton.setText(_translate("PlayerCard", "Дайсы"))
        self.invButton.setText(_translate("PlayerCard", "Инвентарь"))
        self.spellsButton.setText(_translate("PlayerCard", "Заклинания"))


