# Form implementation generated from reading ui file 'RawUI/PlayerCard.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget, QFrame
from UI.SpellCellsObj import Ui_SpellCellObj
from characterclass import Character

class Ui_PlayerCard(QWidget):
    def __init__(self, char = Character()):
        super().__init__()
        self.character = char
        self.setupUi()
    def setupUi(self):
        self.SpellCells = QtWidgets.QGroupBox()
        self.SpellCells.setGeometry(QtCore.QRect(10, 110, 200, 351))
        self.SpellCells.setMaximumSize(QtCore.QSize(200, 3000))
        self.SpellCells.setFlat(False)
        self.SpellCells.setObjectName("SpellCells")
        self.AllCells = QtWidgets.QFrame(parent=self.SpellCells)
        self.AllCells.setGeometry(QtCore.QRect(15, 35, 170, 301))
        self.AllCells.setMinimumSize(QtCore.QSize(0, 0))
        self.AllCells.setStyleSheet("background-color: rgb(124, 124, 124);")
        self.AllCells.setObjectName("AllCells")
        self.AllCellsLayout = QtWidgets.QVBoxLayout(self.AllCells)
        self.AllCellsLayout.setSpacing(2)
        self.AllCellsLayout.setObjectName("AllCellsLayout")
        print(self.character.spellCells)
        for name,count in self.character.spellCells.items():
            line = Ui_SpellCellObj(str(name),int(count))
            self.AllCellsLayout.addWidget(line)


        self.StatusData = QtWidgets.QGroupBox(parent=self)
        self.StatusData.setGeometry(QtCore.QRect(220, 110, 300, 351))
        self.StatusData.setObjectName("StatusData")
        self.layoutWidget = QtWidgets.QWidget(parent=self)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 621, 87))
        self.layoutWidget.setObjectName("layoutWidget")
        self.PrimaryInfo = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.PrimaryInfo.setContentsMargins(0, 0, 0, 0)
        self.PrimaryInfo.setObjectName("PrimaryInfo")
        self.NameArea = QtWidgets.QFrame(parent=self.layoutWidget)
        self.NameArea.setMaximumSize(QtCore.QSize(16777215, 85))
        self.NameArea.setStyleSheet("background-color: rgb(42, 42, 42);")
        self.NameArea.setObjectName("NameArea")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.NameArea)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NameText = QtWidgets.QLabel(parent=self.NameArea)
        self.NameText.setMaximumSize(QtCore.QSize(16777215, 60))
        self.NameText.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.NameText.setWordWrap(True)
        self.NameText.setObjectName("NameText")
        self.horizontalLayout.addWidget(self.NameText)
        self.LevelData = QtWidgets.QVBoxLayout()
        self.LevelData.setObjectName("LevelData")
        self.LevelText = QtWidgets.QPushButton(parent=self.NameArea)
        self.LevelText.setMinimumSize(QtCore.QSize(0, 42))
        self.LevelText.setMaximumSize(QtCore.QSize(85, 16777215))
        self.LevelText.setObjectName("LevelText")
        self.LevelData.addWidget(self.LevelText)
        self.ExpText = QtWidgets.QLabel(parent=self.NameArea)
        self.ExpText.setStyleSheet("font-size: 13pt;")
        self.ExpText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ExpText.setObjectName("ExpText")
        self.LevelData.addWidget(self.ExpText)
        self.horizontalLayout.addLayout(self.LevelData)
        self.PrimaryInfo.addWidget(self.NameArea)
        self.MainChars = QtWidgets.QFrame(parent=self.layoutWidget)
        self.MainChars.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.MainChars.setObjectName("MainChars")
        self.layoutChars = QtWidgets.QGridLayout(self.MainChars)
        self.layoutChars.setObjectName("layoutChars")
        self.BGText = QtWidgets.QLabel(parent=self.MainChars)
        self.BGText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BGText.setWordWrap(True)
        self.BGText.setObjectName("BGText")
        self.layoutChars.addWidget(self.BGText, 1, 1, 1, 1)
        self.RaceText = QtWidgets.QLabel(parent=self.MainChars)
        self.RaceText.setStyleSheet("")
        self.RaceText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.RaceText.setObjectName("RaceText")
        self.layoutChars.addWidget(self.RaceText, 0, 1, 1, 1)
        self.ClassText = QtWidgets.QLabel(parent=self.MainChars)
        self.ClassText.setStyleSheet("")
        self.ClassText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ClassText.setObjectName("ClassText")
        self.layoutChars.addWidget(self.ClassText, 0, 0, 1, 1)
        self.WVText = QtWidgets.QLabel(parent=self.MainChars)
        self.WVText.setStyleSheet("")
        self.WVText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.WVText.setWordWrap(True)
        self.WVText.setObjectName("WVText")
        self.layoutChars.addWidget(self.WVText, 1, 0, 1, 1)
        self.PrimaryInfo.addWidget(self.MainChars)
        self.pushButton = QtWidgets.QPushButton(parent=self)
        self.pushButton.setGeometry(QtCore.QRect(529, 110, 101, 81))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 200, 101, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self)
        self.pushButton_3.setGeometry(QtCore.QRect(530, 290, 101, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 380, 101, 81))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("PlayerCard", "Card"))
        self.SpellCells.setTitle(_translate("PlayerCard", "Ячейки заклинаний"))
        self.StatusData.setTitle(_translate("PlayerCard", "Статусы"))
        self.NameText.setText(_translate("PlayerCard", "Абыбачир Трахов"))
        self.LevelText.setText(_translate("PlayerCard", "20"))
        self.ExpText.setText(_translate("PlayerCard", "355000 / 355000"))
        self.BGText.setText(_translate("PlayerCard", "Гильдийский ремесленник"))
        self.RaceText.setText(_translate("PlayerCard", "Драконорожденный"))
        self.ClassText.setText(_translate("PlayerCard", "Изобретатель"))
        self.WVText.setText(_translate("PlayerCard", "Нейтрально-положительный"))
        self.pushButton.setText(_translate("PlayerCard", "Здоровье"))
        self.pushButton_2.setText(_translate("PlayerCard", "Дайсы"))
        self.pushButton_3.setText(_translate("PlayerCard", "Инвентарь"))
        self.pushButton_4.setText(_translate("PlayerCard", "Заклинания"))


