# Form implementation generated from reading ui file 'RawUI/SpellCellsObject.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRect, QSize, QCoreApplication, Qt, pyqtSignal
from PyQt6.QtWidgets import QWidget, QFrame, QHBoxLayout, QLabel, QCheckBox, QApplication



class Ui_SpellCellObj(QWidget):
    changedSignal = pyqtSignal(str)
    def __init__(self,spLev, count,maxCells):
        super().__init__()
        self.cellLevel = spLev
        self.cellCount = count
        self.maxCount = maxCells
        self.cells = []
        self.setupUi()
    def setupUi(self):
        self.setObjectName("SpellCellObj")
        self.resize(150, 30)
        self.Layout = QFrame(parent=self)
        self.Layout.setGeometry(QRect(0, 0, 150, 30))
        self.Layout.setObjectName("Layout")
        self.horizontalLayout = QHBoxLayout(self.Layout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CellName = QLabel(str(self.cellLevel))
        self.CellName.setMinimumSize(QSize(30, 30))
        self.CellName.setMaximumSize(QSize(30, 30))
        self.CellName.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.CellName.setObjectName("CellName")
        self.horizontalLayout.addWidget(self.CellName)
        for i in range(self.maxCount):
            cell = QCheckBox(parent=self.Layout)
            cell.setStyleSheet("background-color: rgb(92,92,92);")
            cell.setMinimumSize(QtCore.QSize(0, 0))
            cell.setMaximumSize(QtCore.QSize(14, 15))
            cell.setText("")
            cell.setObjectName(f"cell{i}")
            cell.checkStateChanged.connect(self.reCounting)
            if i <= self.cellCount:
                cell.setChecked(True)
            else:cell.setChecked(False)
            self.cells.append(cell)
            self.horizontalLayout.addWidget(cell)
    def reCounting(self):
        output = str(self.cellLevel) + "$0" #name(3)$cells
        for cell in self.cells:
            if cell.isChecked():
                output = output[:-1] + str(int(output[-1]) + 1)
        self.changedSignal.emit(output)




if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    SpellCellObj = QWidget()
    ui = Ui_SpellCellObj()
    ui.setupUi(SpellCellObj)
    SpellCellObj.show()
    sys.exit(app.exec())
