# Form implementation generated from reading ui file 'RawUI/SpellCellsObject.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SpellCellObj(object):
    def setupUi(self, SpellCellObj):
        SpellCellObj.setObjectName("SpellCellObj")
        SpellCellObj.resize(150, 30)
        self.Layout = QtWidgets.QFrame(parent=SpellCellObj)
        self.Layout.setGeometry(QtCore.QRect(0, 0, 150, 30))
        self.Layout.setObjectName("Layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Layout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CellName = QtWidgets.QLabel(parent=self.Layout)
        self.CellName.setMinimumSize(QtCore.QSize(30, 30))
        self.CellName.setMaximumSize(QtCore.QSize(30, 30))
        self.CellName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CellName.setObjectName("CellName")
        self.horizontalLayout.addWidget(self.CellName)
        self.radioButton = QtWidgets.QRadioButton(parent=self.Layout)
        self.radioButton.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton.setMaximumSize(QtCore.QSize(16, 16))
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.Layout)
        self.radioButton_3.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_3.setMaximumSize(QtCore.QSize(16, 16))
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.Layout)
        self.radioButton_2.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_2.setMaximumSize(QtCore.QSize(16, 16))
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.Layout)
        self.radioButton_4.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_4.setMaximumSize(QtCore.QSize(16, 16))
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)

        self.retranslateUi(SpellCellObj)
        QtCore.QMetaObject.connectSlotsByName(SpellCellObj)

    def retranslateUi(self, SpellCellObj):
        _translate = QtCore.QCoreApplication.translate
        SpellCellObj.setWindowTitle(_translate("SpellCellObj", "SpellCellObj"))
        self.CellName.setText(_translate("SpellCellObj", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpellCellObj = QtWidgets.QWidget()
    ui = Ui_SpellCellObj()
    ui.setupUi(SpellCellObj)
    SpellCellObj.show()
    sys.exit(app.exec())
